---
stages:
  - install
  - build
  - publish
  - docker
  - post

variables:
  GO_VERSION: 1.21-alpine
  DOCKER_IMAGE_NAME: cenk1cenk2/vizier

include:
  - project: devops/pipes
    file: /templates/go.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/semantic-release.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/update-docker-hub-readme.gitlab-ci.yml

semantic-release:
  extends: .semantic-release
  stage: publish
  artifacts:
    paths:
      - .tags
      - version.go

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  variables:
    DOCKER_IMAGE_TAGS: latest-$GITLAB_CI_ARCH
    DOCKER_MANIFEST_TARGET: latest
  parallel:
    matrix:
      - GITLAB_CI_ARCH:
          - amd64
          - arm64
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - .tags
      when: always
    - when: never

docker-manifest:
  stage: post
  extends: .docker-manifest-dockerhub
  dependencies:
    - docker-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - .tags
      when: always
    - when: never
  only: null

update-docker-hub-readme:
  stage: post
  extends: .update-docker-hub-readme
  variables:
    README_DESCRIPTION: |
      A very basic and dirty supervisor for multiple tasks running inside a Docker container.
  dependencies: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - .tags
      when: always
    - when: never
  only: null
